export const PROJECT_CATEGORIES = [
  { id: "cat-1", label: "Web Application" },
  { id: "cat-2", label: "Mobile Application" },
  { id: "cat-3", label: "Desktop Application" },
  { id: "cat-4", label: "Cross-Platform Application" },
  { id: "cat-5", label: "Progressive Web App (PWA)" },
  { id: "cat-6", label: "REST API" },
  { id: "cat-7", label: "GraphQL API" },
  { id: "cat-8", label: "Backend Service" },
  { id: "cat-9", label: "Microservice" },
  { id: "cat-10", label: "CLI Tool" },
  { id: "cat-11", label: "Browser Extension" },
  { id: "cat-12", label: "VS Code Extension" },
  { id: "cat-13", label: "IDE Plugin" },
  { id: "cat-14", label: "AI Chatbot" },
  { id: "cat-15", label: "AI Agent" },
  { id: "cat-16", label: "Machine Learning Model" },
  { id: "cat-17", label: "Generative AI Application" },
  { id: "cat-18", label: "Data Analytics Dashboard" },
  { id: "cat-19", label: "Business Intelligence Tool" },
  { id: "cat-20", label: "Automation Tool" },
  { id: "cat-21", label: "Workflow Automation" },
  { id: "cat-22", label: "Game (2D)" },
  { id: "cat-23", label: "Game (3D)" },
  { id: "cat-24", label: "Game Engine Plugin" },
  { id: "cat-25", label: "SaaS Platform" },
  { id: "cat-26", label: "Marketplace Platform" },
  { id: "cat-27", label: "CMS" },
  { id: "cat-28", label: "E-commerce Platform" },
  { id: "cat-29", label: "Portfolio Website" },
  { id: "cat-30", label: "Landing Page" },
  { id: "cat-31", label: "Developer Tool" },
  { id: "cat-32", label: "DevOps Tool" },
  { id: "cat-33", label: "Testing Tool" },
  { id: "cat-34", label: "Library / SDK" },
  { id: "cat-35", label: "IoT Application" },
  { id: "cat-36", label: "Embedded System" },
  { id: "cat-37", label: "Blockchain / Web3 Application" },
  { id: "cat-38", label: "Smart Contract" },
  { id: "cat-39", label: "AR / VR Experience" },
  { id: "cat-40", label: "Wearable Application" },
];

export const PROJECT_DOMAINS = [
  { id: "domain-1", label: "Artificial Intelligence" },
  { id: "domain-2", label: "FinTech" },
  { id: "domain-3", label: "Banking" },
  { id: "domain-4", label: "Healthcare" },
  { id: "domain-5", label: "Mental Health" },
  { id: "domain-6", label: "Education" },
  { id: "domain-7", label: "E-learning" },
  { id: "domain-8", label: "Productivity" },
  { id: "domain-9", label: "Social Networking" },
  { id: "domain-10", label: "Communication" },
  { id: "domain-11", label: "Collaboration" },
  { id: "domain-12", label: "E-commerce" },
  { id: "domain-13", label: "Retail" },
  { id: "domain-14", label: "Marketing" },
  { id: "domain-15", label: "Advertising" },
  { id: "domain-16", label: "Cybersecurity" },
  { id: "domain-17", label: "Privacy" },
  { id: "domain-18", label: "Tourism" },
  { id: "domain-19", label: "Transportation" },
  { id: "domain-20", label: "Logistics" },
  { id: "domain-21", label: "Restaurants" },
  { id: "domain-22", label: "Hospitality" },
  { id: "domain-23", label: "Sports" },
  { id: "domain-24", label: "Fitness & Wellness" },
  { id: "domain-25", label: "Entertainment" },
  { id: "domain-26", label: "Music & Audio" },
  { id: "domain-27", label: "Video Streaming" },
  { id: "domain-28", label: "Real Estate" },
  { id: "domain-29", label: "Construction" },
  { id: "domain-30", label: "Agriculture" },
  { id: "domain-31", label: "Climate & Sustainability" },
  { id: "domain-32", label: "Energy & Utilities" },
  { id: "domain-33", label: "Government & Public Services" },
  { id: "domain-34", label: "Legal Tech" },
  { id: "domain-35", label: "Human Resources" },
  { id: "domain-36", label: "Recruitment" },
  { id: "domain-37", label: "Research & Science" },
  { id: "domain-38", label: "Manufacturing" },
  { id: "domain-39", label: "Non-profit & NGOs" },
  { id: "domain-40", label: "Smart Cities" },
];

export const ESTIMATED_TIMES = [
  { id: "time-1", label: "1–2 Days" },
  { id: "time-2", label: "3–7 Days" },
  { id: "time-3", label: "4–5 Days" },
  { id: "time-4", label: "1–2 Weeks" },
  { id: "time-5", label: "2–4 Weeks" },
  { id: "time-6", label: "1–2 Months" },
  { id: "time-7", label: "3–6 Months" },
  { id: "time-8", label: "6+ Months" },
  { id: "time-9", label: "7+ Months" },
];

export const TECHNOLOGIES = [
  { id: "tech-1", label: "React" },
  { id: "tech-2", label: "React Native" },
  { id: "tech-3", label: "Next.js" },
  { id: "tech-4", label: "Expo" },
  { id: "tech-5", label: "Flutter" },
  { id: "tech-6", label: "Swift" },
  { id: "tech-7", label: "Kotlin" },
  { id: "tech-8", label: "Android" },
  { id: "tech-9", label: "iOS" },
  { id: "tech-10", label: "Vue.js" },
  { id: "tech-11", label: "Nuxt.js" },
  { id: "tech-12", label: "Angular" },
  { id: "tech-13", label: "Svelte" },
  { id: "tech-14", label: "TypeScript" },
  { id: "tech-15", label: "JavaScript" },
  { id: "tech-16", label: "HTML" },
  { id: "tech-17", label: "CSS" },
  { id: "tech-18", label: "Tailwind CSS" },
  { id: "tech-19", label: "Bootstrap" },
  { id: "tech-20", label: "Material UI" },
  { id: "tech-21", label: "Node.js" },
  { id: "tech-22", label: "Express.js" },
  { id: "tech-23", label: "NestJS" },
  { id: "tech-24", label: "Django" },
  { id: "tech-25", label: "Flask" },
  { id: "tech-26", label: "FastAPI" },
  { id: "tech-27", label: "Spring Boot" },
  { id: "tech-28", label: "Laravel" },
  { id: "tech-29", label: "ASP.NET Core" },
  { id: "tech-30", label: "Ruby on Rails" },
  { id: "tech-31", label: "Firebase" },
  { id: "tech-32", label: "Supabase" },
  { id: "tech-33", label: "Appwrite" },
  { id: "tech-34", label: "MongoDB" },
  { id: "tech-35", label: "PostgreSQL" },
  { id: "tech-36", label: "MySQL" },
  { id: "tech-37", label: "SQLite" },
  { id: "tech-38", label: "Redis" },
  { id: "tech-39", label: "Prisma ORM" },
  { id: "tech-40", label: "Drizzle ORM" },
  { id: "tech-41", label: "GraphQL" },
  { id: "tech-42", label: "Apollo GraphQL" },
  { id: "tech-43", label: "REST API" },
  { id: "tech-44", label: "tRPC" },
  { id: "tech-45", label: "Socket.IO" },
  { id: "tech-46", label: "WebSockets" },
  { id: "tech-47", label: "AWS" },
  { id: "tech-48", label: "Google Cloud" },
  { id: "tech-49", label: "Microsoft Azure" },
  { id: "tech-50", label: "Vercel" },
  { id: "tech-51", label: "Netlify" },
  { id: "tech-52", label: "Render" },
  { id: "tech-53", label: "Railway" },
  { id: "tech-54", label: "Cloudflare" },
  { id: "tech-55", label: "Docker" },
  { id: "tech-56", label: "Kubernetes" },
  { id: "tech-57", label: "Git" },
  { id: "tech-58", label: "GitHub Actions" },
  { id: "tech-59", label: "CI/CD" },
  { id: "tech-60", label: "Nginx" },
  { id: "tech-61", label: "TensorFlow" },
  { id: "tech-62", label: "PyTorch" },
  { id: "tech-63", label: "OpenAI API" },
  { id: "tech-64", label: "LangChain" },
  { id: "tech-65", label: "Hugging Face" },
  { id: "tech-66", label: "Pandas" },
  { id: "tech-67", label: "NumPy" },
  { id: "tech-68", label: "Python" },
  { id: "tech-69", label: "Java" },
  { id: "tech-70", label: "C#" },
  { id: "tech-71", label: "C++" },
  { id: "tech-72", label: "Go" },
  { id: "tech-73", label: "Rust" },
  { id: "tech-74", label: "PHP" },
  { id: "tech-75", label: "Ruby" },
  { id: "tech-76", label: "Redux Toolkit" },
  { id: "tech-77", label: "Zustand" },
  { id: "tech-78", label: "Tanstack Query" },
  { id: "tech-79", label: "Redux" },
  { id: "tech-80", label: "Recoil" },
  { id: "tech-81", label: "Stripe" },
  { id: "tech-82", label: "Clerk" },
  { id: "tech-83", label: "Auth0" },
  { id: "tech-84", label: "JWT Authentication" },
  { id: "tech-85", label: "OAuth 2.0" },
  { id: "tech-86", label: "Figma" },
  { id: "tech-87", label: "Framer Motion" },
  { id: "tech-88", label: "React Native Reanimated" },
  { id: "tech-89", label: "Three.js" },
  { id: "tech-90", label: "Unity" },
  { id: "tech-91", label: "Electron.js" },
  { id: "tech-92", label: "Tauri" },
  { id: "tech-93", label: "Capacitor.js" },
  { id: "tech-94", label: "RabbitMQ" },
  { id: "tech-95", label: "Kafka" },
  { id: "tech-96", label: "Elasticsearch" },
  { id: "tech-97", label: "Prometheus" },
  { id: "tech-98", label: "Grafana" },
  { id: "tech-99", label: "Linux" },
  { id: "tech-100", label: "Bash" },
  { id: "tech-101", label: "Sentry" },
  { id: "tech-102", label: "OpenTelemetry" },
  { id: "tech-103", label: "Jest" },
  { id: "tech-104", label: "JUnit" },
  { id: "tech-105", label: "Mockito" },
];

export type SelectionItem = {
  id: string;
  label: string;
};

export enum DIFFICULTY_LEVELS {
  BEGINNER = "Beginner",
  INTERMEDIATE = "Intermediate",
  ADVANCED = "Advanced",
}

export const difficultyStyles = {
  BEGINNER: {
    accent: "bg-emerald-500",
    border: "border-emerald-500",
    text: "text-emerald-600 dark:text-emerald-400",
  },
  INTERMEDIATE: {
    accent: "bg-amber-500",
    border: "border-amber-500",
    text: "text-amber-600 dark:text-amber-400",
  },
  ADVANCED: {
    accent: "bg-rose-500",
    border: "border-rose-500",
    text: "text-rose-600 dark:text-rose-400",
  },
} as const;

export type ProjectFormIcon = "layers" | "globe" | "clock" | "target" | "cpu";

export const ICON_COLORS = {
  layers: {
    light: "#06B6D4",
    dark: "#22D3EE",
  },
  globe: {
    light: "#10B981",
    dark: "#34D399",
  },
  clock: {
    light: "#F59E0B",
    dark: "#FBBF24",
  },
  target: {
    light: "#EF4444",
    dark: "#FB7185",
  },
  cpu: {
    light: "#2563EB",
    dark: "#60A5FA",
  },
} as const;

export const STATIC_SPRING_CONFIGS = {
  damping: 85,
  stiffness: 700,
  mass: 1,
};